name: Compute coverage
on: [pull_request, push]
concurrency: ci-${{ github.ref }}

jobs:
  compute-coverage:
    name: Compute coverage
    runs-on: ubuntu-latest

    steps:
      - name: Install shellspec
        run: wget -O- https://git.io/shellspec | bash -s - -y

      - name: Install other dependencies
        run: sudo apt install -qy kcov

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Compute code coverage
        run: SHELLSPECCMD="shellspec --shell bash" make coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          directory: ./build/coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
