name: Run tests
on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install shellspec
        run: wget -O- https://git.io/shellspec | bash -s - -y

      - name: Install other dependencies
        run: sudo apt install -qy kcov

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Compute code coverage and runs tests
        run: SHELLSPECCMD="shellspec --shell bash" make coverage || true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage
          path: build/coverage

      - name: Upload report artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: report
          path: build/report

  upload-coverage-report:
    name: Upload test report
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4.1.7
        with:
          name: coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  upload-test-report:
    name: Upload test report
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download test report
        uses: actions/download-artifact@v4.1.7
        with:
          name: report

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4.3.1
        with:
          report_paths: results_junit.xml
